name: build

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
        registry-url: 'https://registry.npmjs.org'
      
    - name: Install
      run: |
        npm install yarn -g
        npm install codecov -g
        npm install typescript -g
        yarn install
        yarn install-peer-deps

    - name: Test
      run: |
        yarn test
        codecov

    - name: Build
      run: |
        tsc --build

    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  